function [fitresult, gof] = createFit_gauss(scale, values)
%CREATEFIT(SCALE,VALUES)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : scale
%      Y Output: values
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-May-2019 15:17:47


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( scale, values );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.Normalize = 'on';
opts.StartPoint = [max(values(:)) 0.11384496971432 0.295347916596535];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'values vs. scale', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel scale
ylabel values
grid on


