function [fitresult, gof,yfitted] = Peaksmoother(line, avg_azim)
%CREATEFIT(LINE,AVG_AZIM)
%  Create a fit.
%
%  Data for 'smoothed peaks' fit:
%      X Input : line
%      Y Output: avg_azim
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-May-2019 10:30:38


%% Fit: 'smoothed peaks'.
[xData, yData] = prepareCurveData( line, avg_azim );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 5e-04;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'smoothed peaks' );
h = plot( fitresult, xData, yData );
legend( h, 'avg_azim vs. line', 'smoothed peaks', 'Location', 'NorthEast' );
% Label axes
xlabel line
ylabel avg_azim
grid on

yfitted = feval(fitresult,xData);


